### ISSUE TITLE
Multi GPU pretraining

### ISSUE THREAD

**Issue by HuguesTHOMAS** [CGuangyan-BIT/PointGPT#11]
Hi,

Which command should be used to start the pretraining on multiple GPUs? I guessed from looking at the code, that the parameter `--launcher pytorch` needs to be set. Is there something else to set like environment variables etc?

Best,
Hugues

**Comment by CGuangyan-BIT** [comment]
You can directly specify multiple GPUs, for example, CUDA_VISIBLE_DEVICES=0,1,2,3
