### ISSUE TITLE
The test accuracy is not consistent with the results in your paper

### ISSUE THREAD

**Issue by stylebased** [CGuangyan-BIT/PointGPT#12]
Hi,
When I load the trained model from your link. The accuracy is not consistent with the accuracy you report. For example, in Small Point GPT, you report 94% acc. However, I got 93.27% with the processed test data. Can you explain this problem?
thanks

**Comment by CGuangyan-BIT** [comment]
Hi,
The accuracy in the paper is the result obtained after employing a voting mechanism, while 93.27 is without the voting mechanism. The use of the voting mechanism is explained in the paper and has also been widely adopted by previous methods

**Comment by stylebased** [comment]
thanks
