### ISSUE TITLE
fresh bird ask a code question

### ISSUE THREAD

**Issue by yuanshennnn** [CGuangyan-BIT/PointGPT#13]
in this file PointGPT-1.2\extensions\emd\cuda\emd_kernel.cu 
I get a wrong "error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\bin\\nvcc.exe' failed with exit code 1" when I make 
```
 cd ./extensions/emd
python setup.py install --user
```
but,I found a way through a random query
for example,I changed code 
```
#ifndef _EMD_KERNEL
#define _EMD_KERNEL

#include <cmath>
#include <vector>

#include <ATen/ATen.h>
#include <ATen/cuda/CUDAApplyUtils.cuh>  // at::cuda::getApplyGrid
// #include <THC/THC.h>

#define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
#define CHECK_CONTIGUOUS(x) TORCH_CHECK(x.is_contiguous(), #x " must be contiguous")
#define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
#ifndef CHECK_EQ
#define CHECK_EQ(a, b) assert((a) == (b))
#endif
```
Because I'm still a rookie in code and deep learning,so I can't know whether I accurately do it or not(and my English is not very good,but I am really interested in your code,I would appreciate it if you could give me some advice,thank you very much )

**Comment by CGuangyan-BIT** [comment]
Hi,
I personally think this may be due to issues with your computer's environment configuration, and I think you can try compiling it under Ubuntu

**Comment by yuanshennnn** [comment]
thanks！thank you for your advice！I will study how to use Ubuntu
