### ISSUE TITLE
No scaling factor for RDP.

### ISSUE THREAD

**Issue by nikolai-franke** [CGuangyan-BIT/PointGPT#15]
In the paper you describe the relative direction prompt in equation 5 as $RDP_i = \textrm{PE}((\mathbf{C}_{i+1}^s - \mathbf{C}_i^s) / \parallel \mathbf{C} _{i+1}^s - \mathbf{C} _i^s \parallel_2), \quad i \in \\{ 1, \dots, n' \\}$.

However, in the code I cannot find such scaling factor and it looks like you actually just do $RDP_i = \textrm{PE}(\mathbf{C} _{i+1}^s - \mathbf{C} _i^s)$. 

The relevant lines of code are https://github.com/CGuangyan-BIT/PointGPT/blob/a8bdf85ad469615b3e462a187474d36929a6bbfb/models/PointGPT.py#L380C1-L386C57 and https://github.com/CGuangyan-BIT/PointGPT/blob/a8bdf85ad469615b3e462a187474d36929a6bbfb/models/PointGPT.py#L642C1-L647C1

Does this mean you actually use a relative _position_ prompt instead of a relative direction prompt? Is there a mistake in the paper, is there a mistake in the code, or am I missing something?

**Comment by CGuangyan-BIT** [comment]
Hi!
Thanks for pointing out this error, it was caused by a version error when we were organizing the code, which has now been updated!
