### ISSUE TITLE
Fine-tuning on ScanObjectNN

### ISSUE THREAD

**Issue by root116688** [CGuangyan-BIT/PointGPT#2]
Hi Thanks for released the code
I wonder know how to fine tune ScanObjectNN

I haved Pre-train on ShapeNet
and used CUDA_VISIBLE_DEVICES= python main.py --config cfgs/finetune_scan_hardest.yaml
--finetune_model --exp_name <output_file_name> --ckpts <path/to/pre-trained/model>

But different class number ShapeNet is 40 and ScanObjectNN is 15
and num_group are different Pre-train is 64, but fine tune ScanObjectNN is 128

Thanks alot~

error is below

size mismatch for blocks.cls_head_finetune.8.weight: copying a param with shape torch.Size([40, 256]) from checkpoint, the shape in current model is torch.Size([15, 256]).
size mismatch for blocks.cls_head_finetune.8.bias: copying a param with shape torch.Size([40]) from checkpoint, the shape in current model is torch.Size([15])

**Comment by CGuangyan-BIT** [comment]
Thank you for pointing this out. Since cls_head_finetune was not trained during pre-training, you can simply delete this parameter. We will also modify the code to ensure that the pre-trained model does not include cls_head_finetune.

**Comment by root116688** [comment]
Thanks alot~
