### ISSUE TITLE
Question about ShapeNetPart Datasets

### ISSUE THREAD

**Issue by linchengxing** [CGuangyan-BIT/PointGPT#6]
Hi, thanks for the great work!
I tried to download the ShapeNetPart Datasets from [https://shapenet.cs.stanford.edu/media/shapenetcore_partanno_segmentation_benchmark_v0_normal.zip](url)
But I failed to download it.

**Comment by CGuangyan-BIT** [comment]
I'm sorry you've encountered this issue. This is a relatively common dataset, and you can also search for it on other websites that offer it.

**Comment by linchengxing** [comment]
Thank you for your answer
