### ISSUE TITLE
Pretrained and Post-pretrained PointGPT-B files

### ISSUE THREAD

**Issue by francisco-lourenco-2** [CGuangyan-BIT/PointGPT#7]
Hello,

Thank you so much for your work on PointGPT and for making the pretrained models availble! I was doing some experiments with your work, and I noticed that the download links for the pretrained and post-pretrained PointGPT-B models are the same (both are linked to the pretrained.pth file), so I just wanted to let you know about that :)

**Comment by CGuangyan-BIT** [comment]
Thank you so much for pointing out this issue. We have provided the parameters of post-pretrained PointGPT-B models.

**Comment by francisco-lourenco-2** [comment]
Thank you very much :D
