### ISSUE TITLE
How long did it take to train PointGPT?

### ISSUE THREAD

**Issue by m-a-x-c** [CGuangyan-BIT/PointGPT#9]
- How long did it take to do the auto-regressive SSL pretraining and on what hardware?
- How long did it take to do the post-pretraining and on what hardware?

Thank you.

**Comment by CGuangyan-BIT** [comment]
hello!
When using four NVIDIA RTX 3090 GPUs for training PointGPT-B, the combined time for SSL pretraining and post-pre-training is 75 hours.

**Comment by m-a-x-c** [comment]
Thank you for the information.
